---
- name: "Copy configuration template"
  template:
    src: telegraf.conf.j2
    dest: "{{ telegraf_agent_config_path }}/telegraf.conf"
    owner: telegraf
    group: telegraf
    mode: 0640
  become: yes
  notify:
    - Restart Telegraf

# handle extra plugins exclusive
- name: "Check if extra plugins directory exists in case of exclusive"
  stat:
    path: "{{ telegraf_agent_config_path }}/telegraf.d"
  register: telegraf_directory
  when:
    - telegraf_plugins_extra_exclusive

- name: "Delete telegraf extra plugin path"
  file:
    state: absent
    path: "{{ telegraf_agent_config_path }}/telegraf.d/"
  when:
    - telegraf_plugins_extra_exclusive
    - telegraf_directory.stat.exists
  become: yes
  notify:
    - Restart Telegraf

- name: "Create telegraf extra plugin path"
  file:
    state: directory
    path: "{{ telegraf_agent_config_path }}/telegraf.d/"
    owner: telegraf
    group: telegraf
    mode: 0755
  when:
    - telegraf_plugins_extra_exclusive
    - telegraf_directory.stat.exists
  become: yes
  notify:
    - Restart Telegraf

- name: "Copy telegraf extra plugins"
  template:
    src: "telegraf-extra-plugin.conf.j2"
    dest: "{{ telegraf_agent_config_path }}/telegraf.d/{{ item.key }}.conf"
    owner: telegraf
    group: telegraf
    mode: 0640
  with_dict: "{{ telegraf_plugins_extra }}"
  loop_control:
    label: "{{ item.key }}"
  when:
    - telegraf_plugins_extra is defined
    - telegraf_plugins_extra is iterable
    - item.value.state|default('present') != 'absent'
  become: yes
  notify:
    - Restart Telegraf

- name: "Remove telegraf extra plugins"
  file:
    path: "{{ telegraf_agent_config_path }}/telegraf.d/{{ item.key }}.conf"
    state: absent
  with_dict: "{{ telegraf_plugins_extra }}"
  loop_control:
    label: "{{ item.key }}"
  when:
    - telegraf_plugins_extra is defined
    - telegraf_plugins_extra is iterable
    - item.value.state|default('present') == 'absent'
  become: yes
  notify:
    - Restart Telegraf

- name: "Force restart service after reread config"
  meta: flush_handlers

- name: "Start Telegraf (If it wasn't running)"
  service:
    name: telegraf
    state: started
    enabled: yes
  become: yes
