---
- name: Install on RedHat
  include_tasks: redhat.yml
  when:
    - ansible_os_family == "RedHat"

- name: Configure Unix
  include_tasks: config_unix.yml
  when:
    - ansible_os_family != "Windows"
