---
- name: Use RHEL 7 packages for Fedora
  set_fact:
    telegraf_redhat_releasever: 7
  when:
    - ansible_distribution == "Fedora"

- name: RedHat | Add yum repository
  yum_repository:
    name: influxdb
    description: InfluxDB Repository - RHEl $release
    baseurl: "{{ telegraf_yum_baseurl[ansible_distribution|lower] | default(telegraf_yum_baseurl['default']) }}"
    enabled: true
    gpgcheck: true
    gpgkey: "https://repos.influxdata.com/influxdb.key"
    state: present

- name: RedHat | Install telegraf package
  package:
    name: telegraf
    state: present
  notify: Restart Telegraf
